services:   
  traefik:
    image: traefik:v3.6
    container_name: dev-traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--log.level=DEBUG"
    ports:
      - "8080:8080"  # Traefik dashboard
      - "80:80"      # HTTP traffic
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - web-dev-network

  web:
    container_name: dev-HelloWorldDocker
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - .:/app
    ports:
      - "50005"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`localhost`)"
      - "traefik.http.routers.web.entrypoints=web"
      - "traefik.http.services.web.loadbalancer.server.port=50005"
    networks:
      - web-dev-network
    depends_on:
      - traefik

networks:
  web-dev-network:
    driver: bridge
