services:   
  traefik:
    image: traefik:v3.6
    container_name: prod-traefik
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"      # HTTP traffic
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: unless-stopped
    networks:
      - web-prod-network

  web:
    container_name: prod-HelloWorldDocker
    build: .
    ports:
      - "50005"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`localhost`)"
      - "traefik.http.routers.web.entrypoints=web"
      - "traefik.http.services.web.loadbalancer.server.port=50005"
    restart: unless-stopped
    networks:
      - web-prod-network

networks:
  web-prod-network:
    driver: bridge
